# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ios-Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Socket.IO-Client-Swift', '~> 15.2.0'
pod 'Alamofire'
  # Pods for Ios-Test

  target 'Ios-TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Ios-TestUITests' do
    # Pods for testing
  end

end
