//
// UsersPermissionsRoleAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class UsersPermissionsRoleAPI {
    /**

     - parameter limit: (query) Maximum number of results possible (optional)
     - parameter sort: (query) Sort according to a specific field. (optional)
     - parameter start: (query) Skip a specific number of entries (especially useful for pagination) (optional)
     - parameter : (query) Get entries that matches exactly your input (optional)
     - parameter ne: (query) Get records that are not equals to something (optional)
     - parameter lt: (query) Get record that are lower than a value (optional)
     - parameter lte: (query) Get records that are lower than or equal to a value (optional)
     - parameter gt: (query) Get records that are greater than a value (optional)
     - parameter gte: (query) Get records that are greater than  or equal a value (optional)
     - parameter contains: (query) Get records that contains a value (optional)
     - parameter containss: (query) Get records that contains (case sensitive) a value (optional)
     - parameter _in: (query) Get records that matches any value in the array of values (optional)
     - parameter nin: (query) Get records that doesn&#x27;t match any value in the array of values (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
//    open class func usersPermissionsRolesGet(limit: Int? = nil, sort: String? = nil, start: Int? = nil, : String? = nil, ne: String? = nil, lt: String? = nil, lte: String? = nil, gt: String? = nil, gte: String? = nil, contains: String? = nil, containss: String? = nil, _in: [String]? = nil, nin: [String]? = nil, completion: @escaping ((_ data: [UsersPermissionsRole]?,_ error: Error?) -> Void)) {
//        usersPermissionsRolesGetWithRequestBuilder(limit: limit, sort: sort, start: start, : , ne: ne, lt: lt, lte: lte, gt: gt, gte: gte, contains: contains, containss: containss, _in: _in, nin: nin).execute { (response, error) -> Void in
//            completion(response?.body, error)
//        }
//    }


    /**
     - GET /users-permissions/roles

     - :
       - type: http
       - name: bearerAuth
     - examples: [{contentType=application/json, example=[ {
  "permissions" : [ {
    "controller" : "controller",
    "role" : "role",
    "updated_by" : "updated_by",
    "action" : "action",
    "id" : "id",
    "type" : "type",
    "created_by" : "created_by",
    "enabled" : true,
    "policy" : "policy"
  }, {
    "controller" : "controller",
    "role" : "role",
    "updated_by" : "updated_by",
    "action" : "action",
    "id" : "id",
    "type" : "type",
    "created_by" : "created_by",
    "enabled" : true,
    "policy" : "policy"
  } ],
  "name" : "name",
  "description" : "description",
  "id" : "id",
  "type" : "type",
  "users" : [ {
    "lastName" : "lastName",
    "role" : "role",
    "threads" : [ "threads", "threads" ],
    "avatar" : "avatar",
    "confirmed" : true,
    "created_by" : "created_by",
    "resetPasswordToken" : "resetPasswordToken",
    "firstName" : "firstName",
    "password" : "password",
    "blocked" : true,
    "provider" : "provider",
    "updated_by" : "updated_by",
    "confirmationToken" : "confirmationToken",
    "id" : "id",
    "email" : "email",
    "username" : "username"
  }, {
    "lastName" : "lastName",
    "role" : "role",
    "threads" : [ "threads", "threads" ],
    "avatar" : "avatar",
    "confirmed" : true,
    "created_by" : "created_by",
    "resetPasswordToken" : "resetPasswordToken",
    "firstName" : "firstName",
    "password" : "password",
    "blocked" : true,
    "provider" : "provider",
    "updated_by" : "updated_by",
    "confirmationToken" : "confirmationToken",
    "id" : "id",
    "email" : "email",
    "username" : "username"
  } ]
}, {
  "permissions" : [ {
    "controller" : "controller",
    "role" : "role",
    "updated_by" : "updated_by",
    "action" : "action",
    "id" : "id",
    "type" : "type",
    "created_by" : "created_by",
    "enabled" : true,
    "policy" : "policy"
  }, {
    "controller" : "controller",
    "role" : "role",
    "updated_by" : "updated_by",
    "action" : "action",
    "id" : "id",
    "type" : "type",
    "created_by" : "created_by",
    "enabled" : true,
    "policy" : "policy"
  } ],
  "name" : "name",
  "description" : "description",
  "id" : "id",
  "type" : "type",
  "users" : [ {
    "lastName" : "lastName",
    "role" : "role",
    "threads" : [ "threads", "threads" ],
    "avatar" : "avatar",
    "confirmed" : true,
    "created_by" : "created_by",
    "resetPasswordToken" : "resetPasswordToken",
    "firstName" : "firstName",
    "password" : "password",
    "blocked" : true,
    "provider" : "provider",
    "updated_by" : "updated_by",
    "confirmationToken" : "confirmationToken",
    "id" : "id",
    "email" : "email",
    "username" : "username"
  }, {
    "lastName" : "lastName",
    "role" : "role",
    "threads" : [ "threads", "threads" ],
    "avatar" : "avatar",
    "confirmed" : true,
    "created_by" : "created_by",
    "resetPasswordToken" : "resetPasswordToken",
    "firstName" : "firstName",
    "password" : "password",
    "blocked" : true,
    "provider" : "provider",
    "updated_by" : "updated_by",
    "confirmationToken" : "confirmationToken",
    "id" : "id",
    "email" : "email",
    "username" : "username"
  } ]
} ]}]
     - parameter limit: (query) Maximum number of results possible (optional)
     - parameter sort: (query) Sort according to a specific field. (optional)
     - parameter start: (query) Skip a specific number of entries (especially useful for pagination) (optional)
     - parameter : (query) Get entries that matches exactly your input (optional)
     - parameter ne: (query) Get records that are not equals to something (optional)
     - parameter lt: (query) Get record that are lower than a value (optional)
     - parameter lte: (query) Get records that are lower than or equal to a value (optional)
     - parameter gt: (query) Get records that are greater than a value (optional)
     - parameter gte: (query) Get records that are greater than  or equal a value (optional)
     - parameter contains: (query) Get records that contains a value (optional)
     - parameter containss: (query) Get records that contains (case sensitive) a value (optional)
     - parameter _in: (query) Get records that matches any value in the array of values (optional)
     - parameter nin: (query) Get records that doesn&#x27;t match any value in the array of values (optional)

     - returns: RequestBuilder<[UsersPermissionsRole]> 
     */
//    open class func usersPermissionsRolesGetWithRequestBuilder(limit: Int? = nil, sort: String? = nil, start: Int? = nil, : String? = nil, ne: String? = nil, lt: String? = nil, lte: String? = nil, gt: String? = nil, gte: String? = nil, contains: String? = nil, containss: String? = nil, _in: [String]? = nil, nin: [String]? = nil) -> RequestBuilder<[UsersPermissionsRole]> {
//        let path = "/users-permissions/roles"
//        let URLString = SwaggerClientAPI.basePath + path
//        let parameters: [String:Any]? = nil
//        var url = URLComponents(string: URLString)
//        url?.queryItems = APIHelper.mapValuesToQueryItems([
//                        "_limit": limit?.encodeToJSON(), 
//                        "_sort": sort, 
//                        "_start": start?.encodeToJSON(), 
//                        "_ne": ne, 
//                        "_lt": lt, 
//                        "_lte": lte, 
//                        "_gt": gt, 
//                        "_gte": gte, 
//                        "_contains": contains, 
//                        "_containss": containss, 
//                        "_in": _in, 
//                        "_nin": nin
//        ])
//
//
//        let requestBuilder: RequestBuilder<[UsersPermissionsRole]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()
//
//        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
//    }
    /**

     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func usersPermissionsRolesIdGet(_id: String, completion: @escaping ((_ data: UsersPermissionsRole?,_ error: Error?) -> Void)) {
        usersPermissionsRolesIdGetWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /users-permissions/roles/{id}

     - :
       - type: http
       - name: bearerAuth
     - examples: [{contentType=application/json, example={
  "permissions" : [ {
    "controller" : "controller",
    "role" : "role",
    "updated_by" : "updated_by",
    "action" : "action",
    "id" : "id",
    "type" : "type",
    "created_by" : "created_by",
    "enabled" : true,
    "policy" : "policy"
  }, {
    "controller" : "controller",
    "role" : "role",
    "updated_by" : "updated_by",
    "action" : "action",
    "id" : "id",
    "type" : "type",
    "created_by" : "created_by",
    "enabled" : true,
    "policy" : "policy"
  } ],
  "name" : "name",
  "description" : "description",
  "id" : "id",
  "type" : "type",
  "users" : [ {
    "lastName" : "lastName",
    "role" : "role",
    "threads" : [ "threads", "threads" ],
    "avatar" : "avatar",
    "confirmed" : true,
    "created_by" : "created_by",
    "resetPasswordToken" : "resetPasswordToken",
    "firstName" : "firstName",
    "password" : "password",
    "blocked" : true,
    "provider" : "provider",
    "updated_by" : "updated_by",
    "confirmationToken" : "confirmationToken",
    "id" : "id",
    "email" : "email",
    "username" : "username"
  }, {
    "lastName" : "lastName",
    "role" : "role",
    "threads" : [ "threads", "threads" ],
    "avatar" : "avatar",
    "confirmed" : true,
    "created_by" : "created_by",
    "resetPasswordToken" : "resetPasswordToken",
    "firstName" : "firstName",
    "password" : "password",
    "blocked" : true,
    "provider" : "provider",
    "updated_by" : "updated_by",
    "confirmationToken" : "confirmationToken",
    "id" : "id",
    "email" : "email",
    "username" : "username"
  } ]
}}]
     - parameter _id: (path)  

     - returns: RequestBuilder<UsersPermissionsRole> 
     */
    open class func usersPermissionsRolesIdGetWithRequestBuilder(_id: String) -> RequestBuilder<UsersPermissionsRole> {
        var path = "/users-permissions/roles/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<UsersPermissionsRole>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter body: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func usersPermissionsRolesPost(body: NewUsersPermissionsRole, completion: @escaping ((_ data: UsersPermissionsRole?,_ error: Error?) -> Void)) {
        usersPermissionsRolesPostWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /users-permissions/roles

     - :
       - type: http
       - name: bearerAuth
     - examples: [{contentType=application/json, example={
  "permissions" : [ {
    "controller" : "controller",
    "role" : "role",
    "updated_by" : "updated_by",
    "action" : "action",
    "id" : "id",
    "type" : "type",
    "created_by" : "created_by",
    "enabled" : true,
    "policy" : "policy"
  }, {
    "controller" : "controller",
    "role" : "role",
    "updated_by" : "updated_by",
    "action" : "action",
    "id" : "id",
    "type" : "type",
    "created_by" : "created_by",
    "enabled" : true,
    "policy" : "policy"
  } ],
  "name" : "name",
  "description" : "description",
  "id" : "id",
  "type" : "type",
  "users" : [ {
    "lastName" : "lastName",
    "role" : "role",
    "threads" : [ "threads", "threads" ],
    "avatar" : "avatar",
    "confirmed" : true,
    "created_by" : "created_by",
    "resetPasswordToken" : "resetPasswordToken",
    "firstName" : "firstName",
    "password" : "password",
    "blocked" : true,
    "provider" : "provider",
    "updated_by" : "updated_by",
    "confirmationToken" : "confirmationToken",
    "id" : "id",
    "email" : "email",
    "username" : "username"
  }, {
    "lastName" : "lastName",
    "role" : "role",
    "threads" : [ "threads", "threads" ],
    "avatar" : "avatar",
    "confirmed" : true,
    "created_by" : "created_by",
    "resetPasswordToken" : "resetPasswordToken",
    "firstName" : "firstName",
    "password" : "password",
    "blocked" : true,
    "provider" : "provider",
    "updated_by" : "updated_by",
    "confirmationToken" : "confirmationToken",
    "id" : "id",
    "email" : "email",
    "username" : "username"
  } ]
}}]
     - parameter body: (body)  

     - returns: RequestBuilder<UsersPermissionsRole> 
     */
    open class func usersPermissionsRolesPostWithRequestBuilder(body: NewUsersPermissionsRole) -> RequestBuilder<UsersPermissionsRole> {
        let path = "/users-permissions/roles"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<UsersPermissionsRole>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter role: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func usersPermissionsRolesRoleDelete(role: String, completion: @escaping ((_ data: UploadBody?,_ error: Error?) -> Void)) {
        usersPermissionsRolesRoleDeleteWithRequestBuilder(role: role).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - DELETE /users-permissions/roles/{role}

     - :
       - type: http
       - name: bearerAuth
     - examples: [{contentType=application/json, example={
  "foo" : "foo"
}}]
     - parameter role: (path)  

     - returns: RequestBuilder<UploadBody> 
     */
    open class func usersPermissionsRolesRoleDeleteWithRequestBuilder(role: String) -> RequestBuilder<UploadBody> {
        var path = "/users-permissions/roles/{role}"
        let rolePreEscape = "\(role)"
        let rolePostEscape = rolePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{role}", with: rolePostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<UploadBody>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter body: (body)  
     - parameter role: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func usersPermissionsRolesRolePut(body: NewUsersPermissionsRole, role: String, completion: @escaping ((_ data: UsersPermissionsRole?,_ error: Error?) -> Void)) {
        usersPermissionsRolesRolePutWithRequestBuilder(body: body, role: role).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - PUT /users-permissions/roles/{role}

     - :
       - type: http
       - name: bearerAuth
     - examples: [{contentType=application/json, example={
  "permissions" : [ {
    "controller" : "controller",
    "role" : "role",
    "updated_by" : "updated_by",
    "action" : "action",
    "id" : "id",
    "type" : "type",
    "created_by" : "created_by",
    "enabled" : true,
    "policy" : "policy"
  }, {
    "controller" : "controller",
    "role" : "role",
    "updated_by" : "updated_by",
    "action" : "action",
    "id" : "id",
    "type" : "type",
    "created_by" : "created_by",
    "enabled" : true,
    "policy" : "policy"
  } ],
  "name" : "name",
  "description" : "description",
  "id" : "id",
  "type" : "type",
  "users" : [ {
    "lastName" : "lastName",
    "role" : "role",
    "threads" : [ "threads", "threads" ],
    "avatar" : "avatar",
    "confirmed" : true,
    "created_by" : "created_by",
    "resetPasswordToken" : "resetPasswordToken",
    "firstName" : "firstName",
    "password" : "password",
    "blocked" : true,
    "provider" : "provider",
    "updated_by" : "updated_by",
    "confirmationToken" : "confirmationToken",
    "id" : "id",
    "email" : "email",
    "username" : "username"
  }, {
    "lastName" : "lastName",
    "role" : "role",
    "threads" : [ "threads", "threads" ],
    "avatar" : "avatar",
    "confirmed" : true,
    "created_by" : "created_by",
    "resetPasswordToken" : "resetPasswordToken",
    "firstName" : "firstName",
    "password" : "password",
    "blocked" : true,
    "provider" : "provider",
    "updated_by" : "updated_by",
    "confirmationToken" : "confirmationToken",
    "id" : "id",
    "email" : "email",
    "username" : "username"
  } ]
}}]
     - parameter body: (body)  
     - parameter role: (path)  

     - returns: RequestBuilder<UsersPermissionsRole> 
     */
    open class func usersPermissionsRolesRolePutWithRequestBuilder(body: NewUsersPermissionsRole, role: String) -> RequestBuilder<UsersPermissionsRole> {
        var path = "/users-permissions/roles/{role}"
        let rolePreEscape = "\(role)"
        let rolePostEscape = rolePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{role}", with: rolePostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<UsersPermissionsRole>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
