//
// EmailTestBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EmailTestBody: Codable {

    public var foo: String?

    public init(foo: String? = nil) {
        self.foo = foo
    }


}
