//
// Message.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Message: Codable {

    public var _id: String
    public var text: String
    public var sender: MessageSender?
    public var read: Bool?
    public var delivered: Bool?
    public var thread: MessageThread?

    public init(_id: String, text: String, sender: MessageSender? = nil, read: Bool? = nil, delivered: Bool? = nil, thread: MessageThread? = nil) {
        self._id = _id
        self.text = text
        self.sender = sender
        self.read = read
        self.delivered = delivered
        self.thread = thread
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case text
        case sender
        case read
        case delivered
        case thread
    }

}
