//
// MessageThread.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MessageThread: Codable {

    public var _id: String
    public var title: String?
    public var participents: [String]?
    public var messages: [String]?
    public var createdBy: String?
    public var updatedBy: String?

    public init(_id: String, title: String? = nil, participents: [String]? = nil, messages: [String]? = nil, createdBy: String? = nil, updatedBy: String? = nil) {
        self._id = _id
        self.title = title
        self.participents = participents
        self.messages = messages
        self.createdBy = createdBy
        self.updatedBy = updatedBy
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case title
        case participents
        case messages
        case createdBy = "created_by"
        case updatedBy = "updated_by"
    }

}
