//
// Thread.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Thread: Codable {

    public var _id: String
    public var title: String?
    public var participents: [ThreadParticipents]?
    public var messages: [ThreadMessages]?

    public init(_id: String, title: String? = nil, participents: [ThreadParticipents]? = nil, messages: [ThreadMessages]? = nil) {
        self._id = _id
        self.title = title
        self.participents = participents
        self.messages = messages
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case title
        case participents
        case messages
    }

}
