//
// ThreadParticipents.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ThreadParticipents: Codable {

    public var _id: String
    public var username: String
    public var email: String
    public var provider: String?
    public var password: String?
    public var resetPasswordToken: String?
    public var confirmationToken: String?
    public var confirmed: Bool?
    public var blocked: Bool?
    public var role: String?
    public var avatar: String?
    public var firstName: String?
    public var lastName: String?
    public var threads: [String]?
    public var createdBy: String?
    public var updatedBy: String?

    public init(_id: String, username: String, email: String, provider: String? = nil, password: String? = nil, resetPasswordToken: String? = nil, confirmationToken: String? = nil, confirmed: Bool? = nil, blocked: Bool? = nil, role: String? = nil, avatar: String? = nil, firstName: String? = nil, lastName: String? = nil, threads: [String]? = nil, createdBy: String? = nil, updatedBy: String? = nil) {
        self._id = _id
        self.username = username
        self.email = email
        self.provider = provider
        self.password = password
        self.resetPasswordToken = resetPasswordToken
        self.confirmationToken = confirmationToken
        self.confirmed = confirmed
        self.blocked = blocked
        self.role = role
        self.avatar = avatar
        self.firstName = firstName
        self.lastName = lastName
        self.threads = threads
        self.createdBy = createdBy
        self.updatedBy = updatedBy
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case username
        case email
        case provider
        case password
        case resetPasswordToken
        case confirmationToken
        case confirmed
        case blocked
        case role
        case avatar
        case firstName
        case lastName
        case threads
        case createdBy = "created_by"
        case updatedBy = "updated_by"
    }

}
