//
// UsersPermissionsRolePermissions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UsersPermissionsRolePermissions: Codable {

    public var _id: String
    public var type: String
    public var controller: String
    public var action: String
    public var enabled: Bool
    public var policy: String?
    public var role: String?
    public var createdBy: String?
    public var updatedBy: String?

    public init(_id: String, type: String, controller: String, action: String, enabled: Bool, policy: String? = nil, role: String? = nil, createdBy: String? = nil, updatedBy: String? = nil) {
        self._id = _id
        self.type = type
        self.controller = controller
        self.action = action
        self.enabled = enabled
        self.policy = policy
        self.role = role
        self.createdBy = createdBy
        self.updatedBy = updatedBy
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case type
        case controller
        case action
        case enabled
        case policy
        case role
        case createdBy = "created_by"
        case updatedBy = "updated_by"
    }

}
