//
// UsersPermissionsUser.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UsersPermissionsUser: Codable {

    public var _id: String
    public var username: String
    public var email: String
    public var provider: String?
    public var confirmed: Bool?
    public var blocked: Bool?
    public var role: UsersPermissionsUserRole?
    public var firstName: String?
    public var lastName: String?
    public var threads: [MessageThread]?
    public var avatar: String?

    public init(_id: String, username: String, email: String, provider: String? = nil, confirmed: Bool? = nil, blocked: Bool? = nil, role: UsersPermissionsUserRole? = nil, firstName: String? = nil, lastName: String? = nil, threads: [MessageThread]? = nil, avatar: String? = nil) {
        self._id = _id
        self.username = username
        self.email = email
        self.provider = provider
        self.confirmed = confirmed
        self.blocked = blocked
        self.role = role
        self.firstName = firstName
        self.lastName = lastName
        self.threads = threads
        self.avatar = avatar
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case username
        case email
        case provider
        case confirmed
        case blocked
        case role
        case firstName
        case lastName
        case threads
        case avatar
    }

}
